# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx12G
org.gradle.daemon=false


minecraft_version=1.20.1
minecraft_version_range=1.20.1
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

cc_version=1.114.2
cosmos_version=0.0.7.3
vs2_mc_version=120
vs2_version=2.3.0-beta.7
vs_core_version=1.1.0+b19b27c4a4
registrate_version = MC1.20-1.3.11
create_minecraft_version = 1.20.1
create_version = 6.0.8-289
flywheel_minecraft_version = 1.20.1
flywheel_version = 0.6.10

mod_id=vs_orbit
mod_name=VS Orbit
mod_license=GPL v3
mod_version=0.0.4.2
mod_group_id=net.cn_good_grass.vs_orbit
mod_authors=\u00a7dCN_GOOD_GRASS
mod_description=\u00a76Add motion in space in Cosmic Horizons.\n\u00a77Thanks to SpaceEye and JCM for their help.
